apiVersion: apps/v1
kind: Deployment
metadata:
  name: building-apps-deploy
  labels:
    app: devops-accelerate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-accelerate
  template:
    metadata:
      labels:
        app: devops-accelerate
    spec:
      containers:
      - name: building-apps-container
        image: iamfydel/building-apps
